In [1]:
import pandas as pd
import numpy as np
import itertools
import sys

def read_fasta_file():
    '''
    used for load fasta data and transformd into numpy.array format
    '''
    fh = open('../C.elegans.txt', 'r')
    seq = []
    for line in fh:
        if line.startswith('>'):
            continue
        else:
            seq.append(line.replace('\n', '').replace('\r', ''))
    fh.close()
    matrix_data = np.array([list(e) for e in seq])
    print(matrix_data)
    return matrix_data

def fetch_singleline_features_withoutN(sequence):
    alphabet="ACGT"
    k_num=2
    two_sequence=[]
    for index,data in enumerate(sequence):
        if index <(len(sequence)-k_num+1):
            two_sequence.append("".join(sequence[index:(index+k_num)]))
    parameter=[e for e in itertools.product([0,1],repeat=4)]
    record=[0 for x in range(int(pow(4,k_num)))]
    matrix=["".join(e) for e in itertools.product(alphabet, repeat=k_num)] # AA AU AC AG UU UC ...
    final=[]
    for index,data in enumerate(two_sequence):
        if data in matrix:
            final.extend(parameter[matrix.index(data)])
            record[matrix.index(data)]+=1
            final.append(record[matrix.index(data)]*1.0/(index+1))
    return final

matrix_data=read_fasta_file()
features_data=[]
for index,sequence in enumerate(matrix_data):
    features_data.append(fetch_singleline_features_withoutN(sequence))
print(np.array(features_data).shape)    


[['A' 'C' 'G' ... 'T' 'T' 'T']
 ['A' 'C' 'T' ... 'C' 'G' 'C']
 ['T' 'G' 'G' ... 'G' 'A' 'T']
 ...
 ['C' 'A' 'T' ... 'G' 'C' 'G']
 ['G' 'A' 'C' ... 'G' 'A' 'G']
 ['G' 'C' 'T' ... 'A' 'G' 'T']]
(3108, 200)


In [3]:
    sequence=matrix_data[0]
    alphabet="ACGT"
    k_num=2
    two_sequence=[]
    for index,data in enumerate(sequence):
        if index <(len(sequence)-k_num+1):
            two_sequence.append("".join(sequence[index:(index+k_num)]))
    parameter=[e for e in itertools.product([0,1],repeat=4)]
    record=[0 for x in range(int(pow(4,k_num)))]
    matrix=["".join(e) for e in itertools.product(alphabet, repeat=k_num)] # AA AU AC AG UU UC ...
    final=[]
    for index,data in enumerate(two_sequence):
        if data in matrix:
            final.extend(parameter[matrix.index(data)])
            record[matrix.index(data)]+=1
            final.append(record[matrix.index(data)]*1.0/(index+1))    

In [11]:
sequence

(3108, 200)


In [27]:
two_sequence   

['AC',
 'CG',
 'GT',
 'TG',
 'GA',
 'AG',
 'GC',
 'CT',
 'TG',
 'GA',
 'AT',
 'TG',
 'GA',
 'AC',
 'CT',
 'TC',
 'CA',
 'AC',
 'CA',
 'AC',
 'CT',
 'TT',
 'TA',
 'AC',
 'CT',
 'TA',
 'AG',
 'GG',
 'GC',
 'CA',
 'AT',
 'TT',
 'TC',
 'CC',
 'CT',
 'TC',
 'CG',
 'GT',
 'TT',
 'TT']

In [26]:
print(final)

[0, 0, 0, 1, 1.0, 0, 1, 1, 0, 0.5, 1, 0, 1, 1, 0.3333333333333333, 1, 1, 1, 0, 0.25, 1, 0, 0, 0, 0.2, 0, 0, 1, 0, 0.16666666666666666, 1, 0, 0, 1, 0.14285714285714285, 0, 1, 1, 1, 0.125, 1, 1, 1, 0, 0.2222222222222222, 1, 0, 0, 0, 0.2, 0, 0, 1, 1, 0.09090909090909091, 1, 1, 1, 0, 0.25, 1, 0, 0, 0, 0.23076923076923078, 0, 0, 0, 1, 0.14285714285714285, 0, 1, 1, 1, 0.13333333333333333, 1, 1, 0, 1, 0.0625, 0, 1, 0, 0, 0.058823529411764705, 0, 0, 0, 1, 0.16666666666666666, 0, 1, 0, 0, 0.10526315789473684, 0, 0, 0, 1, 0.2, 0, 1, 1, 1, 0.14285714285714285, 1, 1, 1, 1, 0.045454545454545456, 1, 1, 0, 0, 0.043478260869565216, 0, 0, 0, 1, 0.20833333333333334, 0, 1, 1, 1, 0.16, 1, 1, 0, 0, 0.07692307692307693, 0, 0, 1, 0, 0.07407407407407407, 1, 0, 1, 0, 0.03571428571428571, 1, 0, 0, 1, 0.06896551724137931, 0, 1, 0, 0, 0.1, 0, 0, 1, 1, 0.06451612903225806, 1, 1, 1, 1, 0.0625, 1, 1, 0, 1, 0.06060606060606061, 0, 1, 0, 1, 0.029411764705882353, 0, 1, 1, 1, 0.14285714285714285, 1, 1, 0, 1, 0.083333333

In [9]:
print(features_data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [31]:
[[array([-100.,    7.,    1., ...,  -14.,  -14.,    7.]),
  array([0., 1., 1., ..., 0., 0., 0.])],
 [array([   7., -100.,  -14., ...,  -11.,  -23.,   -8.]),
  array([1., 0., 1., ..., 0., 0., 0.])],
 [array([   1.,  -14., -100., ...,  -20.,    1.,   -8.]),
  array([1., 1., 0., ..., 0., 0., 0.])]]

NameError: name 'array' is not defined

In [38]:
qa=[1,2],[3,4],[5,6],[7,8]
qa


([1, 2], [3, 4], [5, 6], [7, 8])